variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'     
    SolutionBaseName: 'DFC.App.JobProfiles.HowToBecome'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.8.6
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

jobs:

#Build and test resources
- job: BuildArmTemplates
  steps:
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: $(ArmTemplateRoot)

#Build and test application
- job: BuildDotNetCore
  displayName: Build-DotNetCore
  steps:
  # Build DFC.App.JobProfiles.HowToBecome
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-sonar.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 2.2.402
      PublishWebApp: true
      TestSuffix: UnitTests

  # Build DFC.App.JobProfiles.HowToBecome.MessageFunctionApp
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).MessageFunctionApp
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 2.2.402
      PublishWebApp: true

#Build integration tests
- job: BuildDotNetCore
  displayName: Build-DotNetCore
  steps:
  # Build DFC.Api.JobProfiles.HowToBecome.Tests.API.IntegrationTests (no test project)
  - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).Tests.API.IntegrationTests
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 2.2.402
      PublishWebApp: true
